name: portfolio website

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    protfolio_pipeline:
        runs-on: ubuntu-latest

        name: Checkout Repository

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      
        - name: Run tests
          run: |
              python manage.py test