name: portfolio website

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    protfolio_pipeline:
        runs-on: ubuntu-latest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          DEBUG: ${{ secrets.DEBUG }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          

        name: Checkout Repository

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      
        - name: Run tests
          run: |
              python manage.py test
        
        # - name: Deploy
        #   if: ${{ github.event_name == 'push' && github.ref =='refs/heads/main' && !contains(toJson(github.event.commits.*.message),'#skip')   }}
        #   env: 
        #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        #   run: |
        #     curl "$deploy_url"

